### ISSUE TITLE
Script 1-setup.sh do not work (without sudo installed)

### ISSUE THREAD

**Issue by RoSky7791** [itiligent/Guacamole-Install#22]
I want to use your script in Debian 12. I also wanta reverse proxy using Let's Encrypt. 

I added my user to sudo group with "usermod -aG sudo"

I made a tar -xf on https://github.com/itiligent/Guacamole-Install/archive/refs/tags/1.5.3.2.tar.gz

I made chmod +x 1-setup.sh && chmod +x 2-install-guacamole.sh && chmod +x 3-install-nginx.sh && chmod +x 4a-install-tls-self-signed-nginx.sh && chmod +x 4b-install-tls-letsencrypt-nginx.sh

When I configure let's Encrypt, after adding the email address, the script crashes

![image](https://github.com/itiligent/Guacamole-Install/assets/82846871/b8082b44-f553-44da-a217-a1bf7d8cf289)

![image](https://github.com/itiligent/Guacamole-Install/assets/82846871/d971b50d-a585-4884-abda-88d3b6034981)
It Does not find the commande.

Is it normal ?

**Comment by RoSky7791** [comment]
To complete my issue, at the begenning of executing 1-setup.sh, i have some missing commands 
![image](https://github.com/itiligent/Guacamole-Install/assets/82846871/7d717bcc-8dc1-4e3a-9744-feb87e7a094b)

**Comment by itiligent** [comment]
The script installs Lets Encrypt works fine on a fresh Debian 12 install... see my below test output. 

The script lines referenced in your errors seem to relate to multiple problems with  settings at your end.

- the script is having an issue discovering/setting/parsing a valid IP address for certificate setup
- the script is not able to succesfully issue various commands as sudo.
Troubleshooting tips:
- What distro are you using?  (Is this a cloud image or a local fresh install from ISO?)  See the prerequisites readme for cloud images
 - Do you have the sudo package installed? (or are there other OS and sudo restrictions in place?)


![image](https://github.com/itiligent/Guacamole-Install/assets/94789708/0ef72bb4-0ce1-4d35-b9a8-c46f235a05d3)

**Comment by RoSky7791** [comment]
Thanks for your reply ! 

I am using a fresh ISO of Debian 12 last version. Moreover, even if I keep default parameters when using your script (without using a reverse proxy, Let's encrypt, etc.), your script still crashes

**Comment by RoSky7791** [comment]
May can you tell me every commands you used before executing your script please ?

Thank you very much

**Comment by itiligent** [comment]
There are no commands to issue other than running the script from the pasted link. The only requirement is to be logged in with a user that has sudo rights (In order to make a one-sep installer, the script has to install in a number of security contexts and keep many shell enviroment variables common between all scripts - so we install as a $SUDO_USER 

confirm that the sudo package is installed. 
create a brand new user, then add that user to the sudoers group. 
In a FRESH shell, login as the new user and run the script from the paste link again. 
[https://phoenixnap.com/kb/how-to-create-sudo-user-on-ubuntu](https://phoenixnap.com/kb/how-to-create-sudo-user-on-ubuntu)

**Comment by RoSky7791** [comment]
I added 'marc' usr to the sudoers group (with usermod -aG sudo marc)

I still have the same issue when I start your script : 
![image](https://github.com/itiligent/Guacamole-Install/assets/82846871/c3d963ee-9dee-414d-82f1-a9a472f78999)
Lines 181, 208, 209 : sudo : unknown command

**Comment by RoSky7791** [comment]
I have a new issue :

![image](https://github.com/itiligent/Guacamole-Install/assets/82846871/3b11be23-75ca-4c4c-864c-9179356c5e7e)

**Comment by RoSky7791** [comment]
I installed mariadb before using your script, I still have issues :

![image](https://github.com/itiligent/Guacamole-Install/assets/82846871/d13afa8f-7baa-4219-aafe-c5f6be3d87c7)

**Comment by RoSky7791** [comment]
The script worked and installed everything. But I have a new Issue : 
![image](https://github.com/itiligent/Guacamole-Install/assets/82846871/06f405b8-b008-4475-8b18-905d776ae0a9)
It seems that I have missing tomcat 9 packets. When I want to go on my https://..... or http://1.2.3.4:8080/guacamole, it does not work

**Comment by itiligent** [comment]
For the help of others who may read this, please post your resolution for the first issue. Did you not have sudo installed? Were there any other factors that were different from a default install that you ?  

For the new question please create a new issue. I dont understand your question. You must take some extra effort to decribe your issue, all relevant factors, things you've tried to resolve and the steps to reproduce it. Saying it doesnt work is not enough so it is important to get to the bottom of what you are doing that is different from a fresh (minimal) Debian 12 netinstall.

**Comment by itiligent** [comment]
For you new issue I also need to know the install choices you made... for example the http(s) links you reference wont work if you set up self signed TLS, letsencrypt or  just Nginx on port 80. This is by design as the firewall locks this side channel down so gucamole cant be accessed witout the proxy.  Even if you chose not to install Nginx, the default link will actually be http://1.2.3.4:8080 (the option to remove the gucamole directory from the URL is a script **default.**
Look to the very clear and carefully written descriptions on screen or in script comments to undertand first what you are running and why.
