### ISSUE TITLE
Itiligent name is kept in customized branding.jar

### ISSUE THREAD

**Issue by pdtit** [itiligent/Guacamole-Install#26]
**Describe the issue:**
- I updated the branding.jar from /etc/guacamole/extensions with custom settings (new logo png, updated info in en.json translations,...). 
- Issue 1: New logo is visible, although 3x (size = 602 x 244 - where to adapt the correct size? 
- Issue 2: the Itiligent name remains visible on the logon screen - where to change this in the settings files? (couldn't find any trace in the branding.jar)

**Logs / screenshots / error outputs etc**
![image](https://github.com/itiligent/Guacamole-Install/assets/27549824/e0139bc2-0e9f-4b4c-8059-8580a5567b1e)

**Troubleshooting steps already taken?:**
I also tried removing the branding.jar, and restarting guacd - this resulted in reverting back to the default white layout and guacamole logo, but that also still has Itiligent as name. So this makes me feel that name is not stored as part of the branding.jar settings files

**Comment by itiligent** [comment]
When you delte the branding .jar there should be no name leftover. Where are you seeing the itiligent name? Refresh browser cashe perhaps?  There is nothing hard coded in realtion to that.  This took me AGES to figure out, as the official documentation on it is so poor. 

Take a look inside baranding.jar under /translations/en.json for the company name change. (You can also set the fonts for this test in the custom-theme. css file too I think I recall.

In terms of getting your logo to display right, this is where a little css knowledge comes in handy (of which I dont have!) It also depends on the size and pixel dimenanios of your image

The area in the css that adjusts the logo is here:
```
.login-ui .login-dialog .logo {
    background-image: url('app/ext/custom-namespace/images/logo.png');
    width: 7em;
    height:	7em;
    -webkit-background-size: 7em auto;

}

.login-ui .login-dialog {
    background-color: #000000;
    color: #ececec;
}

.login-ui .login-dialog .version .app-name {
    font-weight: 300;
    text-transform: none;
    text-align: center;
    font-size: 2.25em;
    color: #ececec;
    font-family: arial black, sans-serif;
}
```
Pay close attention to the width: 7em and hight 7em. These conrtol the x & y sizing. Google on these "em" figures for more detail theres so many options on how to set up css.. easiest to just expermient changing values say 7 to 5 to 3 and see what happens to you your logo. Do this for for hight and width. You can also make the logon box larger by adding 
```
under .login-ui .login-dialog,
max-width: 4in;
```
try messing about with these settings until you arrive at what you want. Let me know how you get on with the remaining company name, I cant see how that could/should be happening.

**Comment by itiligent** [comment]
just had another thought. Your logo is wrapping and scaling. The value for    `webkit-background-size: 7em auto` may also have a bearing on this, also try that max-with as suggested above (I dont know if there is max height value also)  Sorry but I'm not a web dev so some of these things I'm sure are simple for the initiated. You could also try chatgpt for some tips

**Comment by pdtit** [comment]
Hi, continued testing this, and it's getting more weird... so tried once more to delete the branding.jar, restart guac, upload my custom.jar, which I renamed to branding.jar, restart guac -> still seeing itiligent, but using the guac default logo this time.

After that, I deleted branding.jar from the /etc/guacamole/extensions folder, restart guac... still the same logon page showing... where I would assume it would be 'forced' to go back to the real guacamole defaults :/

tried clearing cache across all browsers I used, checked local browser app storage and clear everything there... no clue

**Comment by pdtit** [comment]
Another quick update... seems like the guacd restart isn't enough to "reset" it, maybe there's some caching in nginx too? I did a full machine shutdown, which after the restart showed me the default guacamole logon screen. 

Now trying to upload my custom branding.jar and see what happens... will keep you posted

**Comment by itiligent** [comment]
Thanks for the update. Be 100% assured there is no other branding included anywhere and a closer inspection of all the bash scripts will confirm this. 

Here's what I think is the root casue of the screen not updating issue: 
I've seen some browser weirdness similar to what you've described in some very specific scenarios where I'd installed more than one guacamole server _**to the same IP address or same base VM** . 

In this instance, if a different TLS certificate is used or the same IP or system that a previous guac TLS browser connection existed,  I've sometimes had trouble forcing the browser to refresh with the new TLS session. If I rolled back to http://8080 there are no issues. With TLS In some cases only some of the page will update, or just not load at all making me think it was broken. It seemed random but eventually I did see a pattern. Becasue I've not been changing logos this might also be something I would have seen If I were to test that also.

This all suggests that TLS connections are cached in a different way and clearing these out is not a perfect science for the browser to perform... or there is disk remanence occurring due to something else because the TLS sessions are still live and are not fully cleared perhaps. Nginx temporary disk remanence could also be a factor too.  I recall this being much more obvious when I'd installed the root certificate into the local windows cert store - I would sometimes need reboot by system to clear everything. I've not been making too many theme changes so this sort of thing may be more prevalent when you make your first 1st changes after a little time playing with the script at its defauts and coming to terms with how it all works.... you then set of with a custom new build and you encounter this. - does any of this mirror some of the steps you might have taken?

FWIW yesterday I deleted the branding.jar on a local gateway I setup last week (that is using letsencrypt) but it went back to the default setting as expected after a restart of Tomcat. I don’t know if guacd has any bearing on the Java plugins, but I've never had to restart it.  (but I often I test with VMware snapshots, so the reboot-to-refresh thing is something I don't normally do).

**Comment by itiligent** [comment]
I just added this below to the readme.  Please test if you can coz a reboot seems a bit drastic. 
`To revert to the Guacamole default theme, simply delete the branding.jar file from /etc/guacamole/extensions then sudo systemctl restart tomcat[version] && sudo systemctl restart guacd && sudo restart nginx and clear your web browser cache. `

**Comment by rene-bayer** [comment]
I can confirm that the branding is done in the branding.jar only
Everything can be changed there, restarting tomcat is necessary

**Comment by itiligent** [comment]
great and thanks for that info.
