### ISSUE TITLE
Can this update MysticRyuujin / guac-install ?

### ISSUE THREAD

**Issue by bradgillap** [itiligent/Guacamole-Install#27]
More of a question than a feature but I have some existing installs with quite a few users I'd rather not have to rebuild from scratch. 

Is it possible to update an existing install on 1.4 series to 1.5 with this?

**Comment by bradgillap** [comment]
Nevermind I see the upgrade-guac.sh here and tried it. It works.

**Comment by itiligent** [comment]
Thanks Brad and for others reading this..

All things being equal it will work. I've tested upgrades with 1.4x to 1.5x and it works fine., but that equal statement needs a bit more context...

The build & upgrade scripts are based closely on the generic build intructions provided by Apache and was originally inspired by the earlier MysticRyuujin repo. I've added a great deal of packaging around these.

There are many changes and simplifications in my repo comapred to MysticRyuujin, as well as support for later Debian flavours, but the end product still gives compatible installed settings and parameters under MOST situtuations.... 

There are a few areas to be careful of. The old MysticRyuujin script offered a choice of older mariaDB connectors which made life complex between varios distros. I took the approach to standardise on one (more stable and univesal ) MySQL conector/j.  I've also added options for offical or distro provided MySQL database packages, and the distro packages are the default .    

Database schema changes don't look to have happended since a a very long way back (but this is a thing to check for in each new release source.) The script should handle this in any event, but there has been nothing to test with on that for a long time. 

So, as long as the original install was not deviated from the common install paths, user, permissions and packages set out in both approaches then it shoud work ok. Some double checking with package recon and sql scheme updates before you start will of course save a lot of pain later!  Review the scripts before you run them and always test though. 

A final thought: The other `add` scripts in this repo should also be compatible too.
