### ISSUE TITLE
Allow run as root

### ISSUE THREAD

**Issue by CrazyWolf13** [itiligent/Guacamole-Install#39]
**Describe the feature or solution you'd like to see included:**
- Allow the running from the user root

**Is this feature request related to a problem or specific use case?:**
- Yes, many installations only include a root user. Everytime creating a non-root user and then enabling sudo is quite unneccessary, or is there any specific problem when allowing run as root?

**Comment by itiligent** [comment]
Thanks for your input.

You can run the scripts as root by removing the root checks at the top of each script - but I dont recommend this nor would it be apppropriate for this repo to make that change (the main pupose of this repo is the creation of secure remote admin infrastructure) and using everything under root is problematic in a number of ways.  

If a Linux distro does not include a non root user by default - this is not because it is uncessary or somehow better without it-  this is typically a product of a minimal install routine that just provides you more full flexibility and assumes a level of inherent Linux knowledge (eg Debian). For messing about with Linux at home, root may be ok, but to take this approach in any production sense (a main use case for this repo) this would lower overall operational maturity as well as introduce a number of risks and other administrative problems. 

There are a whole range reasons why using root for everything is not the way to go, but the main points relate to when everything is running under root, a whole range of best practices are totally punctured:
Firstly, you will lose the ability to delegate administrative control over individual parts or software aspects of a server, (least priviledge concept is lost) and with this also comes the loss of the ability to audit and log actions of a specific user - (enforcing accountabiltiy is also lost). Furthermore, this repo sets Guacamole to run under a specific service account that is restricted to never allow remote access from any interactive logon session which further enhances the least privilage concept (all online guides for installing Guacamole I've seen fail at this)  and protects against priviledge escalation. Directories containing data are also locked down.  Separating running software under serfvice accounts also allows for tighter security profile or policy templates to be used to further lock down the Linux OS without breaking applications or how users might interact with them  (or your ability to effectively administer things).   Sudo also provides a valuable just in time re-authentication check...which is a a key componded under the zero trust approach...and so on.

I hope this helps.

**Comment by CrazyWolf13** [comment]
Thanks for this explanation, cleared up a lot!

Definitely a good choice to **not** allowroot installation!
